### ISSUE TITLE
function names

### ISSUE THREAD

**Issue by joelgeorgem** [jp-praveen/Rendezvous#16]
Rename functions, if required, to make sense after some time.

Then, start a new branch to implement what we discussed.

**Comment by jp-praveen** [comment]
Yes sir, I renamed some of them. I have implemented what we discussed and got outputs without error messages. I have some doubts about the output. I will do some example checks and report them to you soon.

**Comment by jp-praveen** [comment]
Sir, Unlike the previous main code where many formulas were used to find the position at different times in an orbit, I tried using Lagrange coefficients to find r2 and v2 in an orbit when r1, v1 and dt are given as this was less prone to confusion while coding.

**Comment by jp-praveen** [comment]
Dear Sir, 
      I checked the code by swapping the initial position and velocity values. I got the same sequence in both cases using the book method. I will now use Prussings methods and compare both the results.

**Comment by joelgeorgem** [comment]
Again, I am asking you to work in git framework; not upload to git.

The proof that you are just uploading/copy-pasting is the missing extensions for the file names.

**Comment by joelgeorgem** [comment]
... and the function name not matching with the file name.

**Comment by jp-praveen** [comment]
Sorry sir. I was actually editing the code in the Matlab and went with the flow that I forgot to use Git. I will use Git fully from here on.

**Comment by jp-praveen** [comment]
Dear Sir, 
   I wrote the heuristic algorithm which we discussed, using Prussing's method too and checked it. I have pushed the code from my git to the github. I have also updated some of the codes using the git bash. The debris data are also pushed.
