### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by jp-praveen** [jp-praveen/Rendezvous#19]
Dear Sir,
    I wrote the depth-first algorithm (depth_search.m) but have doubts regarding the same. Can I meet you some time to discuss that?

**Comment by joelgeorgem** [comment]
Let us meet tomorrow at 2:45 PM.

**Comment by jp-praveen** [comment]
Yes Sir.

**Comment by jp-praveen** [comment]
Dear Sir,
          I completed the greedy algorithm (with the position of debris updated at each step) and have updated the same on GitHub. I have started coding the heuristic greedy algorithm and will let you know once I complete it.

**Comment by joelgeorgem** [comment]
Okay. Good. I will take a look.

**Comment by joelgeorgem** [comment]
The initial part in the function `realistic_position` -- reading TLE data -- can be outside the function. You need not read the data file every time the function is called; do it only once in the beginning.

Also, you should re-use the code and already written functions. For example, most of the code in the function `realistic_position` are already written. Instead of cutting and pasting those, call the corresponding functions instead. That will improve the readability of the code and minimize the errors.

**Comment by jp-praveen** [comment]
Dear Sir,
          I have put the reading of TLE data outside the function into the greedy.m file. I have also incorporated the heuristic greedy approach in the already written code so that we can use both approaches in the same code. Shall I meet you to discuss the code and about the reorganization of the files in the branches?
          Actually the main loop in realistic_position is similar to the one in main_code_book function but has a difference in the way the loops are executed and there is also a plotting function in main_code_book. That's why I didn't call main_code_book as a function. But apart from that wherever possible I have used the already existing function. 

Thank you
Sincerely,
Praveen

**Comment by joelgeorgem** [comment]
> Actually the main loop in realistic_position is similar to the one in main_code_book function but has a difference in the way the loops are executed and there is also a plotting function in main_code_book. 

Then both the scripts should have used the same _sub-functions_!

For example, the `main_code_book` should have been of the form
```
for i = 1:N
    subfunction1
    plot
    for j = 1:M
        subfunction2
    end
    subfunction3
end
```
and `realistic_position`

````
for i = 1:M
    subfunction1
    subfunction2
    for j = 1:N
        subfunction3
    end
    subfunction4
end
````
Is that the case?
The example does not have any structural relation to our code; just to drive the point clear.

**Comment by joelgeorgem** [comment]
Will meet mostly on Friday.

Will let you know in case we can meet on Thursday.

**Comment by jp-praveen** [comment]
Yes sir. If I understand correctly, you want me to make local functions in a given main function and then use the local function in different main functions.

**Comment by joelgeorgem** [comment]
Yes.

We will anyway be using these 'local functions' again and again.

**Comment by jp-praveen** [comment]
Yes Sir, I will make the changes.

**Comment by jp-praveen** [comment]
Dear Sir,
       On Thursday and Friday, I had that online Graduate Program interview with a Professor from Auburn University and I was able to answer most of his questions. 
Actually, I encountered some problems while making the sub-functions and would like to discuss it with you. Shall I meet you to discuss about it?
