### ISSUE TITLE
Subroutines

### ISSUE THREAD

**Issue by joelgeorgem** [jp-praveen/Rendezvous#2]
It is a good idea to write multiple functions as separate files and use them in the main program.

For example, a function to compute the position and velocity of a satellite given time since the passage of perigee; a function to compute eccentric anomaly given mean anomaly; and so on ...

**Comment by jp-praveen** [comment]
Yes Sir. It will help the program look better. I will create them.

**Comment by joelgeorgem** [comment]
Let the subroutine function and file name be the same.

Get a complete set of working code and inform me.

**Comment by jp-praveen** [comment]
Yes Sir. I will make the changes and inform you.
