### ISSUE TITLE
Main code

### ISSUE THREAD

**Issue by jp-praveen** [jp-praveen/Rendezvous#3]
Dear Sir,
 I made the changes and used fsolve function instead of writing code for Newton's method. I have also updated the subroutines. But when I run the main code, I noticed that after some waiting time, 'twait', the transfer time always takes a lowest value, 'dt', which equals to the 1st iteration value used for the transfer time and then the graph between tcoast and tmin(tcoast+dt) becomes linear. I have attached the graph between tcoast and tmin. I tried changing the dv_max and the graph shape changes. The first image I have attached is for dv_max=18 km/sec and the second image corresponds to dv_max=10km/sec.

Image1.
![image](https://user-images.githubusercontent.com/55296086/65232131-43701000-daee-11e9-9051-d747bfb610ed.png)

Image2.
![image](https://user-images.githubusercontent.com/55296086/65232701-356ebf00-daef-11e9-9e7e-0adfaa2dc682.png)

**Comment by joelgeorgem** [comment]
I have commented on the commits on the main file and tanomaly_rad. Address them.
