### ISSUE TITLE
function f_prograde 

### ISSUE THREAD

**Issue by jp-praveen** [jp-praveen/Rendezvous#5]
Dear Sir,
       I was checking the function f_prograde with some known inputs and outputs and found that there was a mistake while finding the Lagrange functions. I corrected that mistake and also found out why at some points the transfer time becomes 'zero'. Now the output makes some sense to me. Shall I meet you to discuss more about these problems?

**Comment by joelgeorgem** [comment]
Will today (Wednesday) 10 AM be too early for you?
