### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by joelgeorgem** [jp-praveen/Rendezvous#6]
Let all the file names have .m extension.

Use `fzero` instead of `fsolve`.

**Comment by jp-praveen** [comment]
Sir, if I use fzero, I am not getting enough output points because fzero finds the solution when the function changes its sign, and for many iterations, I think it does not find the root. I changed the extensions to .m type. 
Shall I meet you after 11 because I didn't see your message earlier?

**Comment by joelgeorgem** [comment]
No spaces in file names.

**Comment by jp-praveen** [comment]
Yes sir
