### ISSUE TITLE
DCM

### ISSUE THREAD

**Issue by joelgeorgem** [jp-praveen/Rendezvous#7]
Lines 64 and 69 DCMs in the main code should have (perigee+true_anomaly) instead of (perigee) alone; respective true anomalies for the chaser and the target.

**Comment by joelgeorgem** [comment]
Also, care has to be taken to assign the right sign to the perpendicular component of velocity.

**Comment by jp-praveen** [comment]
Sir, I have a doubt. The radial component will also change its sign after a true anomaly of 180 degrees because it points away from the focus?
