### ISSUE TITLE
Prussing's Paper

### ISSUE THREAD

**Issue by jp-praveen** [jp-praveen/Rendezvous#8]
Dear Sir,
         The code which we first wrote was based on the reference from the book, 'Orbital Mechanics', by Howard Curtis. There is another method to solve the lamberts problem as given by Prussing in his paper, 'A Class of Optimal Two-Impulse Rendezvous Using Multiple-Revolution Lambert Solutions'. I wrote a code based on his method so that we can cross-check the outputs from both the methods.  The main code for Prussings method is in the branch, method 2  (Prussing) with the name, main_code_alt.

**Comment by joelgeorgem** [comment]
Okay.
